spring:
  datasource:
    username: postgres
    password: qwerty
    url: jdbc:postgresql://localhost:5432/pkeke
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

jwt:
  token:
    security: soymun
    validate: 3600000